language: go
go:
  - 1.13.x
git:
  depth: 1
install:
  - go get github.com/rakyll/statik
  - sudo apt install gcc-mingw-w64
  - sudo apt install gcc-arm-linux-gnueabi
before_script:
  - statik -src=models -f
  - chmod +x ./build.sh
script:
  - ./build.sh -r b
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: release/*
  draft: true
  cleanup: true
# script:
#   - go test -coverprofile=coverage.txt -covermode=atomic ./...
# after_success:
#   - bash <(curl -s https://codecov.io/bash)
