language: go
go:
  - 1.13.x
git:
  depth: 1
script:
  - go test -v -race -coverprofile=profile.out -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
