name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Get dependencies and build
        run: |
          sudo apt-get update
          sh -c "$(curl -sSL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task release

      - name: Upload binary files
        uses: actions/upload-artifact@v3
        with:
          name: release_artifacts
          path: release/*